use_directory_urls: false # setting this false makes static html work without --no-directory-url build flag

extra_css:
  - css/extra.css
  
theme:
  name: material
  logo: assets/sclogo.png
  favicon: assets/sclogo_white.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.indexes

copyright: Copyright &copy; Granite Devices Inc

repo_url: https://github.com/Simucube/simucube-docs.github.io
repo_name: Contribute an edit
edit_uri: edit/main/docs/

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/simucube
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/simucube
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/granite-devices
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@simucube_official
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/simucube
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/simucube
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/simucube
    - icon: fontawesome/brands/github
      link: https://github.com/simucube      

site_name: Simucube Online Guide

plugins:
    - mkdocs-video
    - search
    - redirects:
        redirect_maps:
          'ActivePedal/Getting started.md': 'ActivePedal/index.md'
          'Tuner/Download.md': 'Tuner/index.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets:
      auto_append:
        - assets/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
nav:
    - Home: index.md
    - ActivePedal: 
        - ActivePedal/index.md
        - Hazards & safety: ActivePedal/Safety.md
        - Installation:
          - Items needed: ActivePedal/Items needed.md
          - Mechanical adjustments: ActivePedal/Mechanical adjustments.md
          - Mounting: ActivePedal/Mounting.md
          - Cabling: ActivePedal/Cabling.md
        - Using software: 
          - First time setup: ActivePedal/Software/First use.md
          - Configuration and calibration: ActivePedal/Software/Configuration.md
          - Profiles: ActivePedal/Software/Profiles.md
          - Pedal feel: ActivePedal/Software/Pedal feel.md
          - Simulator input mapping: ActivePedal/Software/input mapping.md
          - Effects: ActivePedal/Software/Effects.md
          - Passive pedal setup: ActivePedal/Software/Passive pedal setup.md
        - Game setup: 
          - ActivePedal/games/index.md
          - Overview: ActivePedal/games/index.md
          - Automobilista 2: ActivePedal/games/Automobilista2.md
          - BeamNG.drive: ActivePedal/games/BeamNG.md
          - Codemasters F1: ActivePedal/games/F1.md
          - Dirt Rally 1 & 2: ActivePedal/games/DirtRally.md
          - Forza Motorsport 8: ActivePedal/games/Forza Motorsport 8.md
          - Live for Speed: ActivePedal/games/LFS.md
          - Project CARS: ActivePedal/games/pCARS.md
          - Project CARS 2: ActivePedal/games/pCARS2.md
          - Richard Burns Rally: ActivePedal/games/RBR.md
          - WRC Generations: ActivePedal/games/WRC Generations.md
        - FAQ: ActivePedal/FAQ.md
        - Troubleshooting: ActivePedal/Troubleshooting.md
        - Specifications: ActivePedal/Specifications.md
        - Accessories:
          - Baseplate: ActivePedal/Baseplate.md
          - Heusinkveld adapter: ActivePedal/Heusinkveld adapter.md
    - Throttle:
        - Simucube Throttle/index.md
        - Installation:
            - Items needed: Simucube Throttle/Items needed.md
            - Mechanical adjustments: Simucube Throttle/Mechanical adjustments.md
            - Mounting: Simucube Throttle/Mounting.md
        - Using software: ActivePedal/Software/Passive pedal setup.md
        - Troubleshooting: Simucube Throttle/Troubleshooting.md
        - FAQ: Simucube Throttle/FAQ.md
        - Specifications: Simucube Throttle/Specifications.md
    - Tuner: 
        - Tuner/index.md
        - Change log: Tuner/Changelog.md
        - Command line options: Tuner/Command line options.md
    - Developers:
      - Simucube Link: Developers/Simucube Link.md
      - ActivePedal:
        - Dimensions & 3D models: Developers/ActivePedal/Drawings.md
        - Electrical pinouts: Developers/ActivePedal/Pinouts.md
#        - API: Developers/ActivePedal/API.md
      - Throttle: Developers/Simucube Throttle/Drawings.md